name       : python-dockerpty
version    : 0.4.1
release    : 4
source     :
    - https://pypi.python.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz : 69a9d69d573a0daa31bcd1c0774eeed5c15c295fe719c61aca550ed1393156ce
license    : Apache-2.0
component  : programming.python
summary    : Pseudo-tty handler for docker Python client
description: Pseudo-tty handler for docker Python client
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
